# Generated by Django 4.2.3 on 2023-07-24 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('app_name', models.CharField(max_length=30, verbose_name='application name')),
                ('model_name', models.CharField(max_length=30, verbose_name='model name')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'updated'), (3, 'deleted')], verbose_name='action')),
                ('object_instance', models.TextField(default='[]', verbose_name='object values after the action')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time when the changes were made')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who made the action')),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'User Log',
                'ordering': ('-created_at',),
            },
        ),
    ]
